default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  host: localhost

development:
  <<: *default
  database: soul_link_development

test:
  <<: *default
  database: soul_link_test

production:
  <<: *default
  database: soul_link_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>